engines:
  duplication:
    enabled: true
    config:
      languages:
        python:

  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
exclude_paths:
  - tests/**
  - setup.py
ratings:
  paths:
    - fastapi_satella_metrics/**
